
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Plain process.env access (not the strict `env()` helper) so this
    // never throws when DATABASE_URL is absent, e.g. during `prisma
    // generate` in postinstall before Vercel injects build env vars.
    url: process.env.DATABASE_URL!,
  },
});
